# 1. Load and convert to grayscale

In [1]:
from PIL import Image
import numpy as np

In [4]:
def load(filename, folder = 'data/image/'):
    im=np.array(Image.open(folder+filename).convert('L'))
    return im

im1 = load('4050.png')
print(im1)
# Show the image 
Image.fromarray(im1).show()

[[10  8  7 ... 10  9  5]
 [ 9  8  7 ...  6 10 10]
 [ 9  6  8 ... 10 14 12]
 ...
 [17 16 15 ...  9  6  9]
 [14 16 14 ... 11 11  6]
 [17 19 16 ... 14 15  9]]


# 2. Histogram Equalization

Improve the global contrast of the picture.